# Generated by Django 4.1.7 on 2023-04-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradores_dos_livros',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='fornecedor_livros',
            old_name='cnpj',
            new_name='CNPJ',
        ),
    ]
