# Generated by Django 4.1.7 on 2023-04-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_cpf_compradores_dos_livros_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradores_dos_livros',
            old_name='endereco',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='fornecedor_livros',
            old_name='endereco',
            new_name='endereço',
        ),
    ]
